package com.algorithmlearning.shared

/**
 * Immutable, language-resolved text. The UI never concatenates raw strings, so
 * every screen renders through this catalog.
 */
data class AppStrings(
    val appName: String,
    val dashboardTitle: String,
    val problemsTitle: String,
    val reviewTitle: String,
    val settingsTitle: String,
    val languageLabel: String,
    val switchLanguageAction: String,
    val authLoginTitle: String,
    val authRegisterTitle: String,
    val authEmailLabel: String,
    val authPasswordLabel: String,
    val authSignInAction: String,
    val authCreateAccountAction: String,
    val authSwitchToRegisterAction: String,
    val authSwitchToLoginAction: String,
    val authShowPasswordAction: String,
    val authHidePasswordAction: String,
    val authSignedInAsLabel: String,
    val authSignOutAction: String,
    val authRestoringMessage: String,
    val authMissingCredentialsMessage: String,
    val authInvalidCredentialsMessage: String,
    val authRateLimitedMessage: String,
    val authNetworkErrorMessage: String,
    val authServerErrorMessage: String,
    val authUnexpectedErrorMessage: String,
    val problemSearchLabel: String,
    val problemSearchAction: String,
    val problemDifficultyLabel: String,
    val problemPlatformLabel: String,
    val problemReviewStatusLabel: String,
    val problemRefreshAction: String,
    val problemAddAction: String,
    val problemEmptyMessage: String,
    val problemRetryAction: String,
    val problemLoadFailureMessage: String,
    val problemPreviousPageAction: String,
    val problemNextPageAction: String,
    val problemPageLabel: String,
    val problemTitleLabel: String,
    val problemNotesLabel: String,
    val problemDescriptionLabel: String,
    val problemKeyInsightLabel: String,
    val problemTimeComplexityLabel: String,
    val problemSpaceComplexityLabel: String,
    val problemMistakesLabel: String,
    val problemInterviewNotesLabel: String,
    val problemNewTitle: String,
    val problemEditTitle: String,
    val problemSaveAction: String,
    val problemDeleteAction: String,
    val problemEditAction: String,
    val problemDetailBackAction: String,
    val problemDeleteConfirmTitle: String,
    val problemDeleteConfirmMessage: String,
    val problemDeletedMessage: String,
    val problemOperationFailedMessage: String,
    val problemTitleRequiredMessage: String,
    val problemTagsLabel: String,
    val problemNewTagLabel: String,
    val problemCreateTagAction: String,
    val solutionsTitle: String,
    val solutionLanguageLabel: String,
    val solutionCodeLabel: String,
    val solutionExplanationLabel: String,
    val solutionSaveAction: String,
    val solutionDeleteAction: String,
    val commonDeleteAction: String,
    val commonCancelAction: String,
    val difficultyEasy: String,
    val difficultyMedium: String,
    val difficultyHard: String,
    val platformLeetCode: String,
    val platformHackerRank: String,
    val platformOther: String,
    val reviewNeverReviewed: String,
    val reviewDue: String,
    val reviewScheduled: String,
    val reviewDueEmptyMessage: String,
    val reviewLoadFailureMessage: String,
    val reviewStartThinkingAction: String,
    val reviewRevealHintAction: String,
    val reviewRevealApproachAction: String,
    val reviewRevealSolutionAction: String,
    val reviewRateConfidenceAction: String,
    val reviewThinkInstruction: String,
    val reviewNoHintMessage: String,
    val reviewNoApproachMessage: String,
    val reviewSolutionLabel: String,
    val reviewConfidenceLabel: String,
    val reviewConfidenceHintMessage: String,
    val reviewNoteLabel: String,
    val reviewSubmitAction: String,
    val reviewSubmittedMessage: String,
    val reviewExitAction: String,
    val reviewSelectPrompt: String,
    val problemReviewAction: String,
)

object StringCatalog {
    fun of(language: AppLanguage): AppStrings = when (language) {
        AppLanguage.ENGLISH -> AppStrings(
            appName = "Algorithm Learning",
            dashboardTitle = "Dashboard",
            problemsTitle = "Problems",
            reviewTitle = "Review",
            settingsTitle = "Settings",
            languageLabel = "Language",
            switchLanguageAction = "Switch language",
            authLoginTitle = "Sign in",
            authRegisterTitle = "Create account",
            authEmailLabel = "Email",
            authPasswordLabel = "Password",
            authSignInAction = "Sign in",
            authCreateAccountAction = "Create account",
            authSwitchToRegisterAction = "Need an account? Create one",
            authSwitchToLoginAction = "Already have an account? Sign in",
            authShowPasswordAction = "Show password",
            authHidePasswordAction = "Hide password",
            authSignedInAsLabel = "Signed in as",
            authSignOutAction = "Sign out",
            authRestoringMessage = "Restoring session",
            authMissingCredentialsMessage = "Enter your email and password",
            authInvalidCredentialsMessage = "Email or password is incorrect",
            authRateLimitedMessage = "Too many attempts. Try again later",
            authNetworkErrorMessage = "Network unavailable",
            authServerErrorMessage = "The server failed unexpectedly",
            authUnexpectedErrorMessage = "Something went wrong",
            problemSearchLabel = "Search",
            problemSearchAction = "Search problems",
            problemDifficultyLabel = "Difficulty",
            problemPlatformLabel = "Platform",
            problemReviewStatusLabel = "Review status",
            problemRefreshAction = "Refresh problems",
            problemAddAction = "Add problem",
            problemEmptyMessage = "No problems yet",
            problemRetryAction = "Retry",
            problemLoadFailureMessage = "Unable to load problems",
            problemPreviousPageAction = "Previous page",
            problemNextPageAction = "Next page",
            problemPageLabel = "Page",
            problemTitleLabel = "Title",
            problemNotesLabel = "My Approach",
            problemDescriptionLabel = "Problem summary",
            problemKeyInsightLabel = "Key Insight",
            problemTimeComplexityLabel = "Time Complexity",
            problemSpaceComplexityLabel = "Space Complexity",
            problemMistakesLabel = "Common Mistakes",
            problemInterviewNotesLabel = "Interview Notes",
            problemNewTitle = "New problem",
            problemEditTitle = "Edit problem",
            problemSaveAction = "Save problem",
            problemDeleteAction = "Delete problem",
            problemEditAction = "Edit problem",
            problemDetailBackAction = "Back to problems",
            problemDeleteConfirmTitle = "Delete problem?",
            problemDeleteConfirmMessage = "This also deletes its solutions and review records.",
            problemDeletedMessage = "Problem deleted",
            problemOperationFailedMessage = "Something went wrong",
            problemTitleRequiredMessage = "Title is required",
            problemTagsLabel = "Tags",
            problemNewTagLabel = "New tag",
            problemCreateTagAction = "Create tag",
            solutionsTitle = "Solutions",
            solutionLanguageLabel = "Language",
            solutionCodeLabel = "Solution code",
            solutionExplanationLabel = "Explanation",
            solutionSaveAction = "Save solution",
            solutionDeleteAction = "Delete solution",
            commonDeleteAction = "Delete",
            commonCancelAction = "Cancel",
            difficultyEasy = "Easy",
            difficultyMedium = "Medium",
            difficultyHard = "Hard",
            platformLeetCode = "LeetCode",
            platformHackerRank = "HackerRank",
            platformOther = "Other",
            reviewNeverReviewed = "Never reviewed",
            reviewDue = "Due",
            reviewScheduled = "Scheduled",
            reviewDueEmptyMessage = "No problems are due for review",
            reviewLoadFailureMessage = "Unable to load today's review",
            reviewStartThinkingAction = "Start thinking",
            reviewRevealHintAction = "Reveal hint",
            reviewRevealApproachAction = "Reveal my approach",
            reviewRevealSolutionAction = "Reveal solution",
            reviewRateConfidenceAction = "Rate confidence",
            reviewThinkInstruction = "Think without looking at your notes.",
            reviewNoHintMessage = "No hint saved",
            reviewNoApproachMessage = "No approach saved",
            reviewSolutionLabel = "Solution",
            reviewConfidenceLabel = "Confidence",
            reviewConfidenceHintMessage = "0 = cannot solve, 4 = very familiar",
            reviewNoteLabel = "Review note",
            reviewSubmitAction = "Submit review",
            reviewSubmittedMessage = "Review recorded",
            reviewExitAction = "Back to review list",
            reviewSelectPrompt = "Select a problem to review",
            problemReviewAction = "Review problem",
        )
        AppLanguage.TRADITIONAL_CHINESE -> AppStrings(
            appName = "演算法學習",
            dashboardTitle = "儀表板",
            problemsTitle = "題目",
            reviewTitle = "複習",
            settingsTitle = "設定",
            languageLabel = "語言",
            switchLanguageAction = "切換語言",
            authLoginTitle = "登入",
            authRegisterTitle = "建立帳號",
            authEmailLabel = "電子郵件",
            authPasswordLabel = "密碼",
            authSignInAction = "登入",
            authCreateAccountAction = "建立帳號",
            authSwitchToRegisterAction = "還沒有帳號？建立一個",
            authSwitchToLoginAction = "已有帳號？登入",
            authShowPasswordAction = "顯示密碼",
            authHidePasswordAction = "隱藏密碼",
            authSignedInAsLabel = "已登入身分",
            authSignOutAction = "登出",
            authRestoringMessage = "正在還原工作階段",
            authMissingCredentialsMessage = "請輸入電子郵件與密碼",
            authInvalidCredentialsMessage = "電子郵件或密碼不正確",
            authRateLimitedMessage = "嘗試次數過多，請稍後再試",
            authNetworkErrorMessage = "網路無法連線",
            authServerErrorMessage = "伺服器發生錯誤",
            authUnexpectedErrorMessage = "發生未知錯誤",
            problemSearchLabel = "搜尋",
            problemSearchAction = "搜尋題目",
            problemDifficultyLabel = "難度",
            problemPlatformLabel = "平台",
            problemReviewStatusLabel = "複習狀態",
            problemRefreshAction = "重新載入題目",
            problemAddAction = "新增題目",
            problemEmptyMessage = "尚無題目",
            problemRetryAction = "重試",
            problemLoadFailureMessage = "無法載入題目",
            problemPreviousPageAction = "上一頁",
            problemNextPageAction = "下一頁",
            problemPageLabel = "頁",
            problemTitleLabel = "標題",
            problemNotesLabel = "我的解法",
            problemDescriptionLabel = "題目摘要",
            problemKeyInsightLabel = "關鍵洞察",
            problemTimeComplexityLabel = "時間複雜度",
            problemSpaceComplexityLabel = "空間複雜度",
            problemMistakesLabel = "常見錯誤",
            problemInterviewNotesLabel = "面試筆記",
            problemNewTitle = "新增題目",
            problemEditTitle = "編輯題目",
            problemSaveAction = "儲存題目",
            problemDeleteAction = "刪除題目",
            problemEditAction = "編輯題目",
            problemDetailBackAction = "返回題目列表",
            problemDeleteConfirmTitle = "刪除題目？",
            problemDeleteConfirmMessage = "這會同時刪除其解法與複習紀錄。",
            problemDeletedMessage = "題目已刪除",
            problemOperationFailedMessage = "發生未知錯誤",
            problemTitleRequiredMessage = "標題為必填",
            problemTagsLabel = "標籤",
            problemNewTagLabel = "新增標籤",
            problemCreateTagAction = "建立標籤",
            solutionsTitle = "解法",
            solutionLanguageLabel = "語言",
            solutionCodeLabel = "解法程式碼",
            solutionExplanationLabel = "說明",
            solutionSaveAction = "儲存解法",
            solutionDeleteAction = "刪除解法",
            commonDeleteAction = "刪除",
            commonCancelAction = "取消",
            difficultyEasy = "簡單",
            difficultyMedium = "中等",
            difficultyHard = "困難",
            platformLeetCode = "LeetCode",
            platformHackerRank = "HackerRank",
            platformOther = "其他",
            reviewNeverReviewed = "未複習",
            reviewDue = "待複習",
            reviewScheduled = "已排程",
            reviewDueEmptyMessage = "目前沒有待複習的題目",
            reviewLoadFailureMessage = "無法載入今日複習",
            reviewStartThinkingAction = "開始思考",
            reviewRevealHintAction = "顯示提示",
            reviewRevealApproachAction = "顯示我的解法",
            reviewRevealSolutionAction = "顯示解答",
            reviewRateConfidenceAction = "評分信心度",
            reviewThinkInstruction = "先不要看筆記，試著回想。",
            reviewNoHintMessage = "尚未儲存提示",
            reviewNoApproachMessage = "尚未儲存解法",
            reviewSolutionLabel = "解答",
            reviewConfidenceLabel = "信心度",
            reviewConfidenceHintMessage = "0 = 完全不會，4 = 非常熟悉",
            reviewNoteLabel = "複習筆記",
            reviewSubmitAction = "提交複習",
            reviewSubmittedMessage = "已記錄複習",
            reviewExitAction = "返回複習列表",
            reviewSelectPrompt = "選擇要複習的題目",
            problemReviewAction = "複習題目",
        )
    }
}
