package com.algorithmlearning.app.course
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.verticalScroll
import androidx.compose.foundation.rememberScrollState
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.unit.dp
import com.algorithmlearning.shared.AppStrings
data class CourseActions(val selectCategory:(String?)->Unit,val selectTag:(String?)->Unit,val search:(String)->Unit,val open:(String)->Unit,val back:()->Unit,val retry:()->Unit)
@Composable fun CourseScreen(state:CourseState,strings:AppStrings,actions:CourseActions){when(state){CourseState.Loading->Box(Modifier.fillMaxSize(),contentAlignment=androidx.compose.ui.Alignment.Center){CircularProgressIndicator()};CourseState.Failed->Button(onClick=actions.retry){Text(strings.problemRetryAction)};is CourseState.Detail->Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp).testTag("course-detail")){TextButton(onClick=actions.back){Text(strings.courseBackAction)};Text(state.lesson.summary.englishTitle,style=MaterialTheme.typography.headlineSmall);Text(state.lesson.detail,modifier=Modifier.padding(top=12.dp).testTag("course-full-detail"))};is CourseState.List->CourseList(state,strings,actions)}}
@Composable private fun CourseList(state:CourseState.List,strings:AppStrings,actions:CourseActions){var keyword by remember(state.query.keyword){mutableStateOf(state.query.keyword.orEmpty())};Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp).testTag("course-list")){Text(strings.coursesTitle,style=MaterialTheme.typography.headlineSmall);OutlinedTextField(keyword,{keyword=it;actions.search(it)},label={Text(strings.courseSearchLabel)},modifier=Modifier.fillMaxWidth());Text(strings.courseCategoryLabel,modifier=Modifier.padding(top=12.dp));FlowRow { FilterChip(selected=state.query.category==null,onClick={actions.selectCategory(null)},label={Text(strings.coursesTitle)});state.page.categories.forEach{FilterChip(selected=state.query.category==it.slug,onClick={actions.selectCategory(it.slug)},label={Text(it.displayName)})} };val tags=state.page.items.flatMap{it.tags}.distinct();if(tags.isNotEmpty()){Text(strings.courseTagLabel);FlowRow { FilterChip(selected=state.query.tag==null,onClick={actions.selectTag(null)},label={Text(strings.courseTagLabel)});tags.forEach{FilterChip(selected=state.query.tag==it,onClick={actions.selectTag(it)},label={Text(it)})} }};if(state.page.items.isEmpty())Text(strings.courseEmptyMessage);state.page.items.forEach { lesson->ListItem(headlineContent={Text(lesson.englishTitle)},supportingContent={Text(lesson.tags.joinToString())},modifier=Modifier.testTag("course-${lesson.sourceIdentity}"),trailingContent={TextButton(onClick={actions.open(lesson.sourceIdentity)}){Text(">")}});HorizontalDivider()}}}
