package dev.algorithmlearning.api.problems.api;
import dev.algorithmlearning.api.app.security.CurrentUser; import dev.algorithmlearning.api.problems.application.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.net.URI; import java.util.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping(ProblemsController.PATH) public class ProblemsController { public static final String PATH="/api/v1/problems"; private final ProblemService problems; private final SolutionService solutions; private final CurrentUser user; public ProblemsController(ProblemService problems,SolutionService solutions,CurrentUser user){this.problems=problems;this.solutions=solutions;this.user=user;}
 @GetMapping public PageResponse<Summary> list(@RequestParam(required=false) String q,@RequestParam(required=false) String difficulty,@RequestParam(required=false) String platform,@RequestParam(required=false,name="tagId") List<UUID> tagIds,@RequestParam(required=false) String reviewStatus,@RequestParam(defaultValue="updatedDesc") String sort,@RequestParam(defaultValue="1") @Min(1) int page,@RequestParam(defaultValue="20") @Min(1) @Max(100) int pageSize){
  var result=problems.search(user.id(),new ProblemSearch(q,difficulty,platform,tagIds==null?List.of():tagIds,reviewStatus,sort,page,pageSize)); return new PageResponse<>(result.items().stream().map(Summary::from).toList(),page,pageSize,(int)result.totalItems(),(int)((result.totalItems()+pageSize-1)/pageSize));
 }
 @GetMapping("/{id}") public ResponseEntity<Detail> get(@PathVariable UUID id){return problems.findById(user.id(),id).map(p->ResponseEntity.ok(Detail.from(p,solutions.list(user.id(),p.id())))).orElseGet(()->ResponseEntity.notFound().build());}
 @PostMapping public ResponseEntity<Detail> create(@Valid @RequestBody Write request){var p=problems.create(user.id(),request.toWrite());return ResponseEntity.created(URI.create(PATH+"/"+p.id())).body(Detail.from(p,List.of()));}
 @PutMapping("/{id}") public ResponseEntity<Detail> replace(@PathVariable UUID id,@Valid @RequestBody Write request){return problems.replace(user.id(),id,request.toWrite()).map(p->ResponseEntity.ok(Detail.from(p,solutions.list(user.id(),p.id())))).orElseGet(()->ResponseEntity.notFound().build());}
 @DeleteMapping("/{id}") public ResponseEntity<Void> delete(@PathVariable UUID id){return problems.delete(user.id(),id)?ResponseEntity.noContent().build():ResponseEntity.notFound().build();}
 public record Write(@NotBlank @Size(max=200) String title,@NotBlank String platform,@Size(max=120) String externalProblemId,@Size(max=2000) String externalUrl,@NotBlank String difficulty,@Size(max=20000) String description,@Size(max=20000) String notes,@Size(max=10000) String keyInsight,@Size(max=200) String timeComplexity,@Size(max=200) String spaceComplexity,@Size(max=20000) String mistakes,@Size(max=20000) String interviewNotes,@Size(max=50) List<UUID> tagIds){ProblemWrite toWrite(){return new ProblemWrite(title,platform,externalProblemId,externalUrl,difficulty,description,notes,keyInsight,timeComplexity,spaceComplexity,mistakes,interviewNotes,tagIds);}}
 public record TagSummary(UUID id,String name){static TagSummary from(dev.algorithmlearning.api.tags.application.Tag tag){return new TagSummary(tag.id(),tag.name());}}
 public record PageResponse<T>(List<T> items,int page,int pageSize,int totalItems,int totalPages) { }
 public record ReviewSummary(String status,Integer confidence,java.time.Instant lastReviewedAt,java.time.Instant nextReviewAt,int reviewCount){static ReviewSummary neverReviewed(Problem problem){return new ReviewSummary("neverReviewed",null,null,problem.createdAt(),0);}}
 public record Summary(UUID id,String title,String platform,String externalProblemId,String difficulty,List<TagSummary> tags,ReviewSummary review,java.time.Instant createdAt,java.time.Instant updatedAt){static Summary from(Problem p){return new Summary(p.id(),p.title(),p.platform(),p.externalProblemId(),p.difficulty(),p.tags().stream().map(TagSummary::from).toList(),ReviewSummary.neverReviewed(p),p.createdAt(),p.updatedAt());}}
 public record Detail(UUID id,String title,String platform,String externalProblemId,String externalUrl,String difficulty,List<TagSummary> tags,ReviewSummary review,String description,String notes,String keyInsight,String timeComplexity,String spaceComplexity,String mistakes,String interviewNotes,List<SolutionsController.View> solutions,java.time.Instant createdAt,java.time.Instant updatedAt){static Detail from(Problem p,List<Solution> solutions){return new Detail(p.id(),p.title(),p.platform(),p.externalProblemId(),p.externalUrl(),p.difficulty(),p.tags().stream().map(TagSummary::from).toList(),ReviewSummary.neverReviewed(p),p.description(),p.notes(),p.keyInsight(),p.timeComplexity(),p.spaceComplexity(),p.mistakes(),p.interviewNotes(),solutions.stream().map(SolutionsController.View::from).toList(),p.createdAt(),p.updatedAt());}}
}
