package dev.algorithmlearning.api.courses.api;
import dev.algorithmlearning.api.app.config.ApiProperties; import dev.algorithmlearning.api.courses.application.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.util.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/courses") public class CoursesController {
 private final CourseService courses; private final ApiProperties properties; public CoursesController(CourseService c,ApiProperties p){courses=c;properties=p;}
 @PostMapping("/import") ResponseEntity<List<Lesson>> upsert(@RequestHeader(value="X-Course-Ingestion-Token",required=false) String token,@Valid @RequestBody ImportRequest request){if(properties.course().ingestionToken()==null||properties.course().ingestionToken().isBlank()||!java.security.MessageDigest.isEqual(properties.course().ingestionToken().getBytes(),Objects.toString(token,"").getBytes()))return ResponseEntity.status(HttpStatus.FORBIDDEN).build(); return ResponseEntity.ok(courses.upsert(request.lessons.stream().map(Write::toImport).toList()).stream().map(Lesson::from).toList());}
 @GetMapping Page list(@RequestParam(required=false) String category,@RequestParam(required=false) String tag,@RequestParam(required=false) String keyword,@RequestParam(defaultValue="1") @Min(1) int page,@RequestParam(defaultValue="20") @Min(1) @Max(100) int pageSize){var result=courses.list(category,tag,keyword,page,pageSize);return new Page(courses.categories().stream().map(Category::from).toList(),result.items().stream().map(Lesson::from).toList(),result.page(),result.pageSize(),result.totalItems());}
 @GetMapping("/{sourceIdentity}") ResponseEntity<Lesson> detail(@PathVariable String sourceIdentity){return courses.detail(sourceIdentity).map(x->ResponseEntity.ok(Lesson.from(x))).orElseGet(()->ResponseEntity.notFound().build());}
 record ImportRequest(@NotEmpty List<@Valid Write> lessons){} record Write(@NotBlank String categorySlug,@NotBlank String categoryDisplayName,int categorySortOrder,@NotBlank String sourceIdentity,@NotBlank String sourceMarkdownPath,@NotBlank String englishTitle,@NotEmpty List<@NotBlank String> tags,@NotBlank String detail,@NotBlank String sourceUrl,@NotBlank String sourceType,int sortOrder){CourseImport toImport(){return new CourseImport(categorySlug,categoryDisplayName,categorySortOrder,sourceIdentity,sourceMarkdownPath,englishTitle,tags,detail,sourceUrl,sourceType,sortOrder);}} record Category(String slug,String displayName,int sortOrder){static Category from(CourseCategory x){return new Category(x.slug(),x.displayName(),x.sortOrder());}} record Lesson(String sourceIdentity,Category category,String englishTitle,List<String> tags,String detail,String sourceMarkdownPath,String sourceUrl,String sourceType,int sortOrder){static Lesson from(CourseLesson x){return new Lesson(x.sourceIdentity(),Category.from(x.category()),x.englishTitle(),x.tags(),x.detail(),x.sourceMarkdownPath(),x.sourceUrl(),x.sourceType(),x.sortOrder());}} record Page(List<Category> categories,List<Lesson> items,int page,int pageSize,long totalItems){}
}
