#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
if [[ "$ENV_FILE" == ".env" ]]; then ENV_FILE="infra/env/.env.showcase"; fi
mkdir -p "$(dirname "$ENV_FILE")"

require_value() {
  local key="$1" value="$2"
  if [[ -z "$value" ]]; then
    warn "$key cannot be empty"
    return 1
  fi
}

validate_host() {
  local key="$1" value="$2"
  require_value "$key" "$value" || return 1
  if [[ "$value" == *"://"* || "$value" == *"@"* || "$value" == *"/"* || "$value" == *"?"* || "$value" == *":"* || "$value" == *[[:space:]]* ]]; then
    warn "$key must be only a hostname: no scheme, username, password, port, path, or query"
    return 1
  fi
}

validate_identifier() {
  local key="$1" value="$2"
  require_value "$key" "$value" || return 1
  if [[ "$value" == *"://"* || "$value" == *"@"* || "$value" == *"/"* || "$value" == *"?"* || "$value" == *":"* || "$value" == *[[:space:]]* ]]; then
    warn "$key must be a bare identifier, not a URL or connection string"
    return 1
  fi
}

ask_validated() {
  local key="$1" prompt="$2" validator="$3" value
  while :; do
    ask "$key" "$prompt"
    value="${!key}"
    "$validator" "$key" "$value" && return 0
    warn "please re-enter $key"
  done
}

add_secret_version() {
  local name="$1" value="$2"
  printf '%s' "$value" | gcloud secrets versions add "$name" \
    --project=allenljf-algorithm --data-file=- >/dev/null
  WRITTEN_SECRET+=("$name")
  printf '  %s✓ added%s a new Secret Manager version for %s\n' "$GREEN" "$RESET" "$name"
}

banner "CDS-006 showcase private configuration"

stage "Confirm the isolated showcase boundary"
say "This configures only the new allenljf-algorithm project."
say "It never reads existing production secrets and never writes a secret to git or the local env file."
step "Confirm your gcloud login can administer allenljf-algorithm and that you intend to use the existing Neon database."
if ! gcloud projects describe allenljf-algorithm --format='value(projectId)' >/dev/null; then
  warn "gcloud cannot access allenljf-algorithm. Authenticate the intended operator account, then rerun."
  exit 1
fi
pause "Press Enter to continue."

stage "Collect password-free Neon connection details"
open_url "https://console.neon.tech/app/projects"
step "Open the existing Neon project's Connect dialog. Copy only the direct and pooled hostnames, database name, and the two role names."
warn "Do not paste a connection string containing a password. The wizard accepts hostnames only."
ask_validated NEON_DIRECT_HOST "Direct endpoint hostname (migration Job):" validate_host
ask_validated NEON_POOLER_HOST "Pooled endpoint hostname (serving API):" validate_host
ask_validated NEON_DATABASE_NAME "Database name:" validate_identifier
ask_validated NEON_RUNTIME_USERNAME "Runtime DML role name:" validate_identifier
ask_validated NEON_MIGRATION_USERNAME "Migration DDL role name:" validate_identifier
NEON_MIGRATION_JDBC_URL="jdbc:postgresql://${NEON_DIRECT_HOST}/${NEON_DATABASE_NAME}?sslmode=require&channelBinding=require"
NEON_SERVICE_JDBC_URL="jdbc:postgresql://${NEON_POOLER_HOST}/${NEON_DATABASE_NAME}?sslmode=require&channelBinding=require"

stage "Enter Secret Manager values privately"
say "Each value is hidden while you type and is streamed directly to the matching Secret Manager container."
step "Use distinct strong random values for JWT and refresh-hash keys; use the current passwords for the two Neon roles."
ask_secret JWT_KEY "JWT signing key (at least 32 characters):"
ask_secret REFRESH_HASH_KEY "Refresh hash key (at least 32 characters, distinct):"
ask_secret RUNTIME_DB_PASSWORD "Runtime Neon role password:"
ask_secret MIGRATION_DB_PASSWORD "Migration Neon role password:"
if ! confirm "Add these four values as new versions in allenljf-algorithm Secret Manager now"; then
  warn "no secret version was added; rerun when ready"
  exit 1
fi
add_secret_version algorithm-learning-jwt-key "$JWT_KEY"
add_secret_version algorithm-learning-refresh-hash-key "$REFRESH_HASH_KEY"
add_secret_version algorithm-learning-db-password "$RUNTIME_DB_PASSWORD"
add_secret_version algorithm-learning-db-migration-password "$MIGRATION_DB_PASSWORD"
unset JWT_KEY REFRESH_HASH_KEY RUNTIME_DB_PASSWORD MIGRATION_DB_PASSWORD

stage "Persist non-secret deployment configuration locally"
say "Only password-free JDBC URLs, role names, and the canonical public origin are stored in the ignored local file."
write_env GCP_PROJECT_ID "allenljf-algorithm"
write_env GCP_REGION "asia-east1"
write_env GCP_ARTIFACT_REPOSITORY "algorithm-learning"
write_env GCP_CLOUD_RUN_SERVICE "algorithm-learning-api"
write_env APP_CORS_ALLOWED_ORIGINS "https://allenljf-algorithm.web.app"
write_env NEON_MIGRATION_JDBC_URL "$NEON_MIGRATION_JDBC_URL"
write_env NEON_SERVICE_JDBC_URL "$NEON_SERVICE_JDBC_URL"
write_env NEON_RUNTIME_USERNAME "$NEON_RUNTIME_USERNAME"
write_env NEON_MIGRATION_USERNAME "$NEON_MIGRATION_USERNAME"

stage "Confirm the deployment handoff"
say "Secret versions and the local non-secret deployment configuration are now ready."
say "Do not share the local file or any secret value in chat. The next CDS-006 step builds the API image, deploys the migration Job and serving API, then deploys Hosting."
pause "Press Enter after reviewing the summary."

finish
