#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
# The wizard library already set ENV_FILE to its own default (".env"), so a
# ${ENV_FILE:-...} fallback here would never fire. Replace only that default.
if [[ "$ENV_FILE" == ".env" ]]; then ENV_FILE="infra/env/.env.neon"; fi
mkdir -p "$(dirname "$ENV_FILE")"

# validate_host rejects anything that is not a bare hostname, so a pasted full
# connection string (which carries a password) can never reach a JDBC URL or a
# GitHub Variable.
validate_host() {
  local key="$1" value="$2"
  if [[ -z "$value" ]]; then
    warn "$key is empty; enter the hostname from the Neon Connect dialog"
    return 1
  fi
  if [[ "$value" == *"://"* || "$value" == *"@"* || "$value" == *"/"* || "$value" == *"?"* || "$value" == *":"* || "$value" == *[[:space:]]* ]]; then
    warn "$key must be a bare hostname like ep-xxx.aws.neon.tech; no scheme, user, password, port, or path"
    return 1
  fi
  return 0
}

# validate_identifier rejects a database name or role that is actually a URL.
validate_identifier() {
  local key="$1" value="$2"
  if [[ -z "$value" ]]; then
    warn "$key is empty; enter the name from the Neon Connect dialog"
    return 1
  fi
  if [[ "$value" == *"://"* || "$value" == *"@"* || "$value" == *"/"* || "$value" == *"?"* || "$value" == *":"* || "$value" == *[[:space:]]* ]]; then
    warn "$key must be a bare name, not a URL or connection string"
    return 1
  fi
  return 0
}

# ask_validated re-prompts until the value passes the named validator.
ask_validated() {
  local key="$1" prompt="$2" validator="$3" value
  while :; do
    ask "$key" "$prompt"
    value="${!key}"
    "$validator" "$key" "$value" && return 0
    warn "please re-enter $key"
  done
}

set_environment_var() {
  local name="$1" value="$2"
  if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
    SKIPPED+=("GitHub production variable $name")
    warn "skipped GitHub production variable $name; set it in the opened page"
    return
  fi
  # GitHub rejects an empty variable value, and gh treats an empty --body as
  # "prompt me", so an empty value must delete the variable instead.
  if [[ -z "$value" ]]; then
    gh variable delete "$name" --env production >/dev/null 2>&1 || true
    printf '  %s✓ left empty%s GitHub production variable %s\n' "$GREEN" "$RESET" "$name"
    return
  fi
  if printf '%s' "$value" | gh variable set "$name" --env production >/dev/null 2>&1; then
    printf '  %s✓ set%s GitHub production variable %s\n' "$GREEN" "$RESET" "$name"
    return
  fi
  SKIPPED+=("GitHub production variable $name")
  warn "skipped GitHub production variable $name; set it in the opened page"
}

banner "Neon + Cloud Run setup"

stage "Confirm the Neon delivery boundary"
warn "The committed production workflow is still Cloud SQL-specific. Do not deploy it with Neon values."
say "This wizard prepares non-secret Neon and GitHub Environment configuration only."
say "Run the later Neon workflow migration before triggering a production deployment."
step "Confirm that this is the intended production repository: allenljf/algorithm-learning."
pause "Press Enter once you understand this wizard does not deploy or modify GCP resources."

stage "Neon: collect non-secret connection details"
open_url "https://console.neon.tech/app/projects"
step "Select or create the production Neon project, then open its Connect dialog."
step "Copy the direct endpoint hostname and the pooled (-pooler) endpoint hostname."
step "Record the database name and least-privilege application role name. Do not paste its password here."
ask_validated NEON_DIRECT_HOST "Direct endpoint hostname (for Flyway):" validate_host
ask_validated NEON_POOLER_HOST "Pooled endpoint hostname (for Cloud Run service):" validate_host
ask_validated NEON_DATABASE_NAME "Neon database name:" validate_identifier
ask_validated NEON_DATABASE_USERNAME "Neon application role name:" validate_identifier
NEON_MIGRATION_JDBC_URL="jdbc:postgresql://${NEON_DIRECT_HOST}/${NEON_DATABASE_NAME}?sslmode=require&channelBinding=require"
NEON_SERVICE_JDBC_URL="jdbc:postgresql://${NEON_POOLER_HOST}/${NEON_DATABASE_NAME}?sslmode=require&channelBinding=require"
if [[ "$NEON_MIGRATION_JDBC_URL" == *"@"* || "$NEON_SERVICE_JDBC_URL" == *"@"* ]]; then
  printf '%s\n' 'Refusing to continue: a JDBC URL contains credentials. Re-run and enter hostnames only.' >&2
  exit 1
fi
write_env NEON_DIRECT_HOST "$NEON_DIRECT_HOST"
write_env NEON_POOLER_HOST "$NEON_POOLER_HOST"
write_env NEON_DATABASE_NAME "$NEON_DATABASE_NAME"
write_env NEON_DATABASE_USERNAME "$NEON_DATABASE_USERNAME"
write_env NEON_MIGRATION_JDBC_URL "$NEON_MIGRATION_JDBC_URL"
write_env NEON_SERVICE_JDBC_URL "$NEON_SERVICE_JDBC_URL"
note "Only hostnames, role names, and password-free JDBC URLs were saved to $ENV_FILE."

stage "GCP Secret Manager: enter secret values yourself"
open_url "https://console.cloud.google.com/security/secret-manager?project=alert-study-508214-s5"
step "Create or open algorithm-learning-jwt-key and add a random value of at least 32 characters."
step "Create or open algorithm-learning-refresh-hash-key and add a distinct random value of at least 32 characters."
step "Create or open algorithm-learning-db-password and add only the Neon application role password."
warn "Never paste any secret into this wizard, a GitHub Variable, shell history, source control, or chat."
pause "Press Enter after all three Secret Manager values have been added privately."

stage "GitHub: protect the production Environment"
open_url "https://github.com/allenljf/algorithm-learning/settings/environments"
step "Open or create the production Environment."
step "Restrict deployments to the protected main branch and add any required reviewers."
step "Keep secrets empty: this design uses GitHub OIDC plus GCP Secret Manager, not GitHub credential secrets."
pause "Press Enter after the production Environment protection rules are saved."

stage "GitHub: set production Variables"
open_url "https://github.com/allenljf/algorithm-learning/settings/environments"
say "The wizard can use an authenticated gh CLI to set Environment-scoped Variables after confirmation."
ask GCP_PROJECT_ID "GCP project ID:"; GCP_PROJECT_ID="${GCP_PROJECT_ID:-alert-study-508214-s5}"
ask GCP_REGION "GCP region:"; GCP_REGION="${GCP_REGION:-asia-east1}"
ask GCP_WIF_PROVIDER "WIF provider resource name:"
ask GCP_DEPLOY_SERVICE_ACCOUNT "GCP deploy service-account email:"
ask GCP_ARTIFACT_REPOSITORY "Artifact Registry repository:"; GCP_ARTIFACT_REPOSITORY="${GCP_ARTIFACT_REPOSITORY:-algorithm-learning}"
ask GCP_CLOUD_RUN_SERVICE "Cloud Run service name:"; GCP_CLOUD_RUN_SERVICE="${GCP_CLOUD_RUN_SERVICE:-algorithm-learning-api}"
ask GCP_CORS_ALLOWED_ORIGINS "CORS allowlist (leave empty until Flutter Web has a controlled origin):"
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
write_env GCP_REGION "$GCP_REGION"
write_env GCP_WIF_PROVIDER "$GCP_WIF_PROVIDER"
write_env GCP_DEPLOY_SERVICE_ACCOUNT "$GCP_DEPLOY_SERVICE_ACCOUNT"
write_env GCP_ARTIFACT_REPOSITORY "$GCP_ARTIFACT_REPOSITORY"
write_env GCP_CLOUD_RUN_SERVICE "$GCP_CLOUD_RUN_SERVICE"
write_env GCP_CORS_ALLOWED_ORIGINS "$GCP_CORS_ALLOWED_ORIGINS"
if confirm "Set the listed non-secret Variables in GitHub Environment production using gh now"; then
  set_environment_var GCP_PROJECT_ID "$GCP_PROJECT_ID"
  set_environment_var GCP_REGION "$GCP_REGION"
  set_environment_var GCP_WIF_PROVIDER "$GCP_WIF_PROVIDER"
  set_environment_var GCP_DEPLOY_SERVICE_ACCOUNT "$GCP_DEPLOY_SERVICE_ACCOUNT"
  set_environment_var GCP_ARTIFACT_REPOSITORY "$GCP_ARTIFACT_REPOSITORY"
  set_environment_var GCP_CLOUD_RUN_SERVICE "$GCP_CLOUD_RUN_SERVICE"
  set_environment_var GCP_CORS_ALLOWED_ORIGINS "$GCP_CORS_ALLOWED_ORIGINS"
  set_environment_var NEON_SERVICE_JDBC_URL "$NEON_SERVICE_JDBC_URL"
  set_environment_var NEON_MIGRATION_JDBC_URL "$NEON_MIGRATION_JDBC_URL"
  set_environment_var NEON_DATABASE_USERNAME "$NEON_DATABASE_USERNAME"
else
  warn "Set the values manually in production → Variables before deployment."
fi

stage "Review the handoff boundary"
say "The Neon service URL is for the serving Cloud Run service; the direct URL is only for the Flyway migration Job."
say "Verify both URLs require TLS and contain no password before keeping them as GitHub Variables."
step "Do not run infra/gcp/bootstrap.sh --apply until it has been replaced with the Neon-compatible bootstrap path."
step "Next, update the governed GCP delivery spec, bootstrap tooling, and deployment workflow from Cloud SQL to Neon."
pause "Press Enter to finish without triggering a deployment."

finish
