package dev.algorithmlearning.api.problems.application;
import java.time.Instant; import java.util.*; import org.springframework.transaction.annotation.Transactional;
public final class SolutionService { private final ProblemRepository problems; private final SolutionRepository solutions; public SolutionService(ProblemRepository problems,SolutionRepository solutions){this.problems=problems;this.solutions=solutions;}
 @Transactional public Solution create(UUID owner,UUID problemId,SolutionWrite write){if(problems.findByIdAndUserId(problemId,owner).isEmpty())throw new NoSuchElementException();return solutions.save(from(UUID.randomUUID(),problemId,write,Instant.now(),Instant.now()));}
 public List<Solution> list(UUID owner,UUID problemId){return problems.findByIdAndUserId(problemId,owner).isEmpty()?List.of():solutions.findAllByProblemId(problemId);}
 public Optional<Solution> findById(UUID owner,UUID id){return solutions.findByIdAndUserId(id,owner);}
 @Transactional public Optional<Solution> replace(UUID owner,UUID id,SolutionWrite write){return findById(owner,id).map(old->solutions.save(from(id,old.problemId(),write,old.createdAt(),Instant.now())));}
 @Transactional public boolean delete(UUID owner,UUID id){if(findById(owner,id).isEmpty())return false;solutions.deleteById(id);return true;}
 private static Solution from(UUID id,UUID problemId,SolutionWrite w,Instant created,Instant updated){var language=w.language()==null?"":w.language().trim();if(!Set.of("kotlin","java","python","dart").contains(language))throw new IllegalArgumentException("Invalid solution language.");var code=w.code()==null?"":w.code();var explanation=blank(w.explanation());if(code.length()>100000||(explanation!=null&&explanation.length()>20000)||(code.trim().isEmpty()&&explanation==null))throw new IllegalArgumentException("Invalid solution content.");return new Solution(id,problemId,language,code,explanation,created,updated);} private static String blank(String v){return v==null||v.trim().isEmpty()?null:v.trim();}}
