import java.util.ArrayDeque
import java.util.PriorityQueue
import kotlin.math.*

// Standalone implementations for the 63 lessons that were formerly index-only.
class X217 { fun containsDuplicate(a:IntArray)=a.size!=a.toHashSet().size }
class X271 { fun encode(a:List<String>)=a.joinToString(""){"${it.length}#${it}"}; fun decode(s:String):List<String>{val r=mutableListOf<String>();var i=0;while(i<s.length){val j=s.indexOf('#',i);val n=s.substring(i,j).toInt();r+=s.substring(j+1,j+1+n);i=j+1+n};return r} }
class X36 { fun isValidSudoku(b:Array<CharArray>):Boolean { val seen=HashSet<String>();for(i in 0..8)for(j in 0..8)if(b[i][j]!='.'){val c=b[i][j];if(!seen.add("r$i$c")||!seen.add("c$j$c")||!seen.add("b${i/3}${j/3}$c"))return false};return true} }
class X150 { fun evalRPN(t:Array<String>):Int {val s=ArrayDeque<Int>();for(x in t)if(x in setOf("+","-","*","/")){val b=s.removeLast();val a=s.removeLast();s.addLast(when(x){"+"->a+b;"-"->a-b;"*"->a*b;else->a/b})}else s.addLast(x.toInt());return s.last()} }
class X853 { fun carFleet(target:Int,p:IntArray,s:IntArray):Int {var ans=0;var slow=0.0;for((x,v)in p.zip(s).sortedByDescending{it.first}){val time=(target-x).toDouble()/v;if(time>slow){ans++;slow=time}};return ans} }
class X4 { fun findMedianSortedArrays(a:IntArray,b:IntArray):Double {if(a.size>b.size)return findMedianSortedArrays(b,a);var l=0;var r=a.size;while(l<=r){val i=(l+r)/2;val j=(a.size+b.size+1)/2-i;val al=if(i==0)Int.MIN_VALUE else a[i-1];val ar=if(i==a.size)Int.MAX_VALUE else a[i];val bl=if(j==0)Int.MIN_VALUE else b[j-1];val br=if(j==b.size)Int.MAX_VALUE else b[j];if(al<=br&&bl<=ar)return if((a.size+b.size)%2==0)(max(al,bl).toDouble()+min(ar,br))/2 else max(al,bl).toDouble();if(al>br)r=i-1 else l=i+1};error("sorted inputs required")} }

class LNode(var v:Int){var next:LNode?=null;var random:LNode?=null}
class TNode(var v:Int){var left:TNode?=null;var right:TNode?=null}
class X141 { fun hasCycle(h:LNode?):Boolean {var a=h;var b=h;while(b?.next!=null){a=a?.next;b=b.next?.next;if(a===b)return true};return false} }
class X138 { fun copyRandomList(h:LNode?):LNode? {val m=HashMap<LNode,LNode>();var p=h;while(p!=null){m[p]=LNode(p.v);p=p.next};p=h;while(p!=null){m[p]!!.next=m[p.next];m[p]!!.random=m[p.random];p=p.next};return m[h]} }
class X2 { fun addTwoNumbers(a:LNode?,b:LNode?):LNode? {var x=a;var y=b;var c=0;val d=LNode(0);var p=d;while(x!=null||y!=null||c>0){val z=(x?.v?:0)+(y?.v?:0)+c;c=z/10;p.next=LNode(z%10);p=p.next!!;x=x?.next;y=y?.next};return d.next} }
class X287 { fun findDuplicate(a:IntArray):Int {var s=a[0];var f=a[0];do{s=a[s];f=a[a[f]]}while(s!=f);s=a[0];while(s!=f){s=a[s];f=a[f]};return s} }
class X23 { fun mergeKLists(a:Array<LNode?>):LNode? {val q=PriorityQueue<LNode>(compareBy{it.v});a.filterNotNull().forEach(q::add);val d=LNode(0);var p=d;while(q.isNotEmpty()){val n=q.remove();p.next=n;p=n;if(n.next!=null)q.add(n.next)};return d.next} }
class X25 { fun reverseKGroup(h:LNode?,k:Int):LNode? {val d=LNode(0);d.next=h;var pre=d;while(true){var tail=pre;repeat(k){tail=tail.next?:return d.next};val nxt=tail.next;var p=pre.next;var prev=nxt;while(p!==nxt){val q=p!!.next;p.next=prev;prev=p;p=q};val old=pre.next;pre.next=tail;pre=old!!} } }

class X543 { private var best=0;fun diameterOfBinaryTree(r:TNode?):Int {fun d(n:TNode?):Int{if(n==null)return 0;val a=d(n.left);val b=d(n.right);best=max(best,a+b);return 1+max(a,b)};d(r);return best} }
class X110 { fun isBalanced(r:TNode?):Boolean {fun h(n:TNode?):Int{if(n==null)return 0;val a=h(n.left);val b=h(n.right);if(a<0||b<0||abs(a-b)>1)return -1;return 1+max(a,b)};return h(r)>=0} }
class X100 { fun isSameTree(a:TNode?,b:TNode?):Boolean=if(a==null||b==null)a===b else a.v==b.v&&isSameTree(a.left,b.left)&&isSameTree(a.right,b.right) }
class X572 { fun isSubtree(a:TNode?,b:TNode?):Boolean {fun same(x:TNode?,y:TNode?):Boolean { return if(x==null||y==null) x===y else x.v==y.v&&same(x.left,y.left)&&same(x.right,y.right) };return a!=null&&(same(a,b)||isSubtree(a.left,b)||isSubtree(a.right,b))} }
class X235 { fun lowestCommonAncestor(r:TNode?,p:TNode,q:TNode):TNode? {var n=r;while(n!=null){n=when{p.v<n.v&&q.v<n.v->n.left;p.v>n.v&&q.v>n.v->n.right;else->return n}};return null} }
class X230 { fun kthSmallest(r:TNode?,k:Int):Int {val s=ArrayDeque<TNode>();var n=r;var left=k;while(n!=null||s.isNotEmpty()){while(n!=null){s.addLast(n);n=n.left};n=s.removeLast();if(--left==0)return n.v;n=n.right};error("k") } }

class X703(k:Int,a:IntArray){private val q=PriorityQueue<Int>();private val n=k;init{a.forEach(::add)};fun add(x:Int):Int{q.add(x);if(q.size>n)q.remove();return q.peek()} }
class X1046 { fun lastStoneWeight(a:IntArray):Int {val q=PriorityQueue<Int>(reverseOrder());a.forEach(q::add);while(q.size>1){val x=q.remove()-q.remove();if(x>0)q.add(x)};return q.poll()?:0} }
class X973 { fun kClosest(a:Array<IntArray>,k:Int):Array<IntArray> = a.sortedBy{it[0]*it[0]+it[1]*it[1]}.take(k).toTypedArray() }
class X355 { private data class T(val t:Int,val u:Int,val id:Int);private var clock=0;private val follows=HashMap<Int,MutableSet<Int>>();private val tweets=HashMap<Int,MutableList<T>>();fun postTweet(u:Int,id:Int){tweets.getOrPut(u){mutableListOf()}.add(T(++clock,u,id))};fun getNewsFeed(u:Int)=((follows[u]?:emptySet())+u).flatMap{tweets[it]?:emptyList()}.sortedByDescending{it.t}.take(10).map{it.id};fun follow(a:Int,b:Int){follows.getOrPut(a){mutableSetOf()}.add(b)};fun unfollow(a:Int,b:Int){follows[a]?.remove(b)} }
class X40 { fun combinationSum2(a:IntArray,t:Int):List<List<Int>> {val r=mutableListOf<List<Int>>();val p=mutableListOf<Int>();val s=a.sorted();fun go(i:Int,left:Int){if(left==0){r+=p.toList();return};for(j in i until s.size){if(j>i&&s[j]==s[j-1])continue;if(s[j]>left)break;p+=s[j];go(j+1,left-s[j]);p.removeLast()}};go(0,t);return r} }
class X90 { fun subsetsWithDup(a:IntArray):List<List<Int>> {val r=mutableListOf<List<Int>>();val p=mutableListOf<Int>();val s=a.sorted();fun go(i:Int){r+=p.toList();for(j in i until s.size){if(j>i&&s[j]==s[j-1])continue;p+=s[j];go(j+1);p.removeLast()}};go(0);return r} }
class X22 { fun generateParenthesis(n:Int):List<String>{val r=mutableListOf<String>();fun go(s:String,l:Int,rr:Int){if(s.length==2*n){r+=s;return};if(l<n)go(s+"(",l+1,rr);if(rr<l)go(s+")",l,rr+1)};go("",0,0);return r} }
class X131 { fun partition(s:String):List<List<String>> {val r=mutableListOf<List<String>>();val p=mutableListOf<String>();fun go(i:Int){if(i==s.length){r+=p.toList();return};for(j in i+1..s.length){val x=s.substring(i,j);if(x==x.reversed()){p+=x;go(j);p.removeLast()}}};go(0);return r} }
class X51 { fun solveNQueens(n:Int):List<List<String>>{val r=mutableListOf<List<String>>();val col=HashSet<Int>();val d1=HashSet<Int>();val d2=HashSet<Int>();val b=Array(n){CharArray(n){'.'}};fun go(row:Int){if(row==n){r+=b.map{it.concatToString()};return};for(c in 0 until n)if(c !in col&&row-c !in d1&&row+c !in d2){col+=c;d1+=row-c;d2+=row+c;b[row][c]='Q';go(row+1);b[row][c]='.';col-=c;d1-=row-c;d2-=row+c}};go(0);return r} }

class X212 { fun findWords(b:Array<CharArray>,words:Array<String>):List<String>{val r=HashSet<String>();fun go(i:Int,j:Int,k:Int,w:String,seen:MutableSet<Pair<Int,Int>>){if(k==w.length){r+=w;return};if(i !in b.indices||j !in b[0].indices||b[i][j]!=w[k]||(i to j) in seen)return;seen+=i to j;go(i+1,j,k+1,w,seen);go(i-1,j,k+1,w,seen);go(i,j+1,k+1,w,seen);go(i,j-1,k+1,w,seen);seen-=i to j};for(w in words)for(i in b.indices)for(j in b[0].indices)go(i,j,0,w,mutableSetOf());return r.toList()} }
class X695 { fun maxAreaOfIsland(g:Array<IntArray>):Int{fun go(i:Int,j:Int):Int{if(i !in g.indices||j !in g[0].indices||g[i][j]==0)return 0;g[i][j]=0;return 1+go(i+1,j)+go(i-1,j)+go(i,j+1)+go(i,j-1)};var r=0;for(i in g.indices)for(j in g[0].indices)r=max(r,go(i,j));return r} }
class X286 { fun wallsAndGates(a:Array<IntArray>){val q=ArrayDeque<Pair<Int,Int>>();for(i in a.indices)for(j in a[0].indices)if(a[i][j]==0)q+=i to j;while(q.isNotEmpty()){val(i,j)=q.removeFirst();for((x,y)in arrayOf(i+1 to j,i-1 to j,i to j+1,i to j-1))if(x in a.indices&&y in a[0].indices&&a[x][y]==Int.MAX_VALUE){a[x][y]=a[i][j]+1;q+=x to y}}} }
class X417 { fun pacificAtlantic(h:Array<IntArray>):List<List<Int>>{val m=h.size;val n=h[0].size;fun walk(st:List<Pair<Int,Int>>):Set<Pair<Int,Int>>{val seen=st.toMutableSet();val q=ArrayDeque(st);while(q.isNotEmpty()){val(i,j)=q.removeFirst();for((x,y)in arrayOf(i+1 to j,i-1 to j,i to j+1,i to j-1))if(x in 0 until m&&y in 0 until n&&(x to y) !in seen&&h[x][y]>=h[i][j]){seen+=x to y;q+=x to y}};return seen};val a=walk((0 until m).map{it to 0}+(0 until n).map{0 to it});val b=walk((0 until m).map{it to n-1}+(0 until n).map{m-1 to it});return (a intersect b).map{listOf(it.first,it.second)}} }
class X130 { fun solve(b:Array<CharArray>){fun go(i:Int,j:Int){if(i !in b.indices||j !in b[0].indices||b[i][j]!='O')return;b[i][j]='S';go(i+1,j);go(i-1,j);go(i,j+1);go(i,j-1)};for(i in b.indices){go(i,0);go(i,b[0].lastIndex)};for(j in b[0].indices){go(0,j);go(b.lastIndex,j)};for(i in b.indices)for(j in b[0].indices)b[i][j]=if(b[i][j]=='S')'O' else if(b[i][j]=='O')'X' else b[i][j]} }
class X261 { fun validTree(n:Int,e:Array<IntArray>):Boolean {if(e.size!=n-1)return false;val p=IntArray(n){it};fun f(x:Int):Int{if(p[x]!=x)p[x]=f(p[x]);return p[x]};for(x in e){val a=f(x[0]);val b=f(x[1]);if(a==b)return false;p[a]=b};return true} }
class X323 { fun countComponents(n:Int,e:Array<IntArray>):Int {val p=IntArray(n){it};fun f(x:Int):Int{if(p[x]!=x)p[x]=f(p[x]);return p[x]};var r=n;for(x in e){val a=f(x[0]);val b=f(x[1]);if(a!=b){p[a]=b;r--}};return r} }
class X127 { fun ladderLength(a:String,b:String,w:List<String>):Int {val d=w.toHashSet();if(b !in d)return 0;val q=ArrayDeque<Pair<String,Int>>();q+=a to 1;val seen=hashSetOf(a);while(q.isNotEmpty()){val(s,k)=q.removeFirst();if(s==b)return k;for(i in s.indices)for(c in 'a'..'z'){val x=s.substring(0,i)+c+s.substring(i+1);if(x in d&&seen.add(x))q+=x to k+1}};return 0} }
class X778 { fun swimInWater(g:Array<IntArray>):Int {val n=g.size;val q=PriorityQueue<Triple<Int,Int,Int>>(compareBy{it.first});q+=Triple(g[0][0],0,0);val seen=hashSetOf(0 to 0);var r=0;while(q.isNotEmpty()){val(t,i,j)=q.remove();r=max(r,t);if(i==n-1&&j==n-1)return r;for((x,y)in arrayOf(i+1 to j,i-1 to j,i to j+1,i to j-1))if(x in 0 until n&&y in 0 until n&&seen.add(x to y))q+=Triple(g[x][y],x,y)};return r} }
class X269 { fun alienOrder(w:Array<String>):String {val g=HashMap<Char,MutableSet<Char>>();w.flatMap{it.toList()}.forEach{g.putIfAbsent(it,mutableSetOf())};for(i in 0 until w.size-1){val a=w[i];val b=w[i+1];if(a.startsWith(b)&&a.length>b.length)return "";for(j in 0 until min(a.length,b.length))if(a[j]!=b[j]){g[a[j]]!!+=b[j];break}};val state=HashMap<Char,Int>();val r=StringBuilder();fun dfs(c:Char):Boolean{if(state[c]==1)return false;if(state[c]==2)return true;state[c]=1;for(x in g[c]!!)if(!dfs(x))return false;state[c]=2;r.append(c);return true};return if(g.keys.all(::dfs))r.reverse().toString() else ""} }
class X787 { fun findCheapestPrice(n:Int,f:Array<IntArray>,s:Int,d:Int,k:Int):Int {var cost=IntArray(n){1_000_000_000};cost[s]=0;repeat(k+1){val next=cost.clone();for(x in f)if(cost[x[0]]<1_000_000_000)next[x[1]]=min(next[x[1]],cost[x[0]]+x[2]);cost=next};return if(cost[d]==1_000_000_000)-1 else cost[d]} }
class X213 { fun rob(a:IntArray):Int {if(a.size==1)return a[0];fun go(b:IntArray):Int{var x=0;var y=0;for(v in b){val z=max(y,x+v);x=y;y=z};return y};return max(go(a.copyOfRange(0,a.lastIndex)),go(a.copyOfRange(1,a.size)))} }
class X647 { fun countSubstrings(s:String):Int {var r=0;for(c in s.indices)for(d in 0..1){var l=c;var x=c+d;while(l>=0&&x<s.length&&s[l]==s[x]){r++;l--;x++}};return r} }
class X91 { fun numDecodings(s:String):Int {if(s.isEmpty()||s[0]=='0')return 0;var a=1;var b=1;for(i in 1 until s.length){val c=if(s[i]!='0')b else 0;if(s.substring(i-1,i+1).toInt() in 10..26)a+=b;b=a;a=c+if(s.substring(i-1,i+1).toInt() in 10..26)b else 0};var dp=IntArray(s.length+1);dp[0]=1;dp[1]=1;for(i in 2..s.length){if(s[i-1]!='0')dp[i]+=dp[i-1];if(s.substring(i-2,i).toInt() in 10..26)dp[i]+=dp[i-2]};return dp[s.length]} }
class X152 { fun maxProduct(a:IntArray):Int {var hi=a[0];var lo=a[0];var r=a[0];for(i in 1 until a.size){val x=a[i];val old=hi;hi=max(x,max(old*x,lo*x));lo=min(x,min(old*x,lo*x));r=max(r,hi)};return r} }
class X139 { fun wordBreak(s:String,d:List<String>):Boolean {val set=d.toHashSet();val ok=BooleanArray(s.length+1);ok[0]=true;for(i in 1..s.length)for(j in 0 until i)if(ok[j]&&s.substring(j,i) in set){ok[i]=true;break};return ok[s.length]} }
class X97 { fun isInterleave(a:String,b:String,c:String):Boolean {if(a.length+b.length!=c.length)return false;val d=BooleanArray(b.length+1);d[0]=true;for(j in 1..b.length)d[j]=d[j-1]&&b[j-1]==c[j-1];for(i in 1..a.length){d[0]=d[0]&&a[i-1]==c[i-1];for(j in 1..b.length)d[j]=(d[j]&&a[i-1]==c[i+j-1])||(d[j-1]&&b[j-1]==c[i+j-1])};return d[b.length]} }
class X329 { fun longestIncreasingPath(a:Array<IntArray>):Int {val m=a.size;val n=a[0].size;val memo=Array(m){IntArray(n)};fun go(i:Int,j:Int):Int{if(memo[i][j]>0)return memo[i][j];var r=1;for((x,y)in arrayOf(i+1 to j,i-1 to j,i to j+1,i to j-1))if(x in 0 until m&&y in 0 until n&&a[x][y]>a[i][j])r=max(r,1+go(x,y));memo[i][j]=r;return r};return (0 until m).maxOf{i->(0 until n).maxOf{j->go(i,j)}}} }
class X312 { fun maxCoins(a:IntArray):Int {val b=intArrayOf(1)+a+intArrayOf(1);val d=Array(b.size){IntArray(b.size)};for(len in 2 until b.size)for(l in 0 until b.size-len){val r=l+len;for(k in l+1 until r)d[l][r]=max(d[l][r],b[l]*b[k]*b[r]+d[l][k]+d[k][r])};return d[0][b.lastIndex]} }
class X10 { fun isMatch(s:String,p:String):Boolean {val d=Array(s.length+1){BooleanArray(p.length+1)};d[0][0]=true;for(j in 2..p.length)if(p[j-1]=='*')d[0][j]=d[0][j-2];for(i in 1..s.length)for(j in 1..p.length)if(p[j-1]=='*')d[i][j]=d[i][j-2]||((p[j-2]=='.'||p[j-2]==s[i-1])&&d[i-1][j]) else d[i][j]=(p[j-1]=='.'||p[j-1]==s[i-1])&&d[i-1][j-1];return d[s.length][p.length]} }
class X134 { fun canCompleteCircuit(g:IntArray,c:IntArray):Int {var total=0;var tank=0;var start=0;for(i in g.indices){val x=g[i]-c[i];total+=x;tank+=x;if(tank<0){start=i+1;tank=0}};return if(total<0)-1 else start} }
class X846 { fun isNStraightHand(a:IntArray,k:Int):Boolean {if(a.size%k>0)return false;val m=java.util.TreeMap<Int,Int>();a.forEach{m[it]=(m[it]?:0)+1};while(m.isNotEmpty()){val x=m.firstKey();for(v in x until x+k){val n=m[v]?:return false;if(n==1)m.remove(v) else m[v]=n-1}};return true} }
class X1899 { fun mergeTriplets(a:Array<IntArray>,t:IntArray):Boolean {var x=0;var y=0;var z=0;for(v in a)if(v[0]<=t[0]&&v[1]<=t[1]&&v[2]<=t[2]){x=max(x,v[0]);y=max(y,v[1]);z=max(z,v[2])};return x==t[0]&&y==t[1]&&z==t[2]} }
class X763 { fun partitionLabels(s:String):List<Int>{val last=IntArray(26);s.forEachIndexed{i,c->last[c-'a']=i};val r=mutableListOf<Int>();var end=0;var start=0;s.forEachIndexed{i,c->end=max(end,last[c-'a']);if(i==end){r+=i-start+1;start=i+1}};return r} }
class X678 { fun checkValidString(s:String):Boolean {var lo=0;var hi=0;for(c in s){if(c=='('){lo++;hi++}else if(c==')'){lo--;hi--}else{lo--;hi++};if(hi<0)return false;if(lo<0)lo=0};return lo==0} }
class X252 { fun canAttendMeetings(a:Array<IntArray>):Boolean {val s=a.sortedBy{it[0]};return (1 until s.size).all{s[it][0]>=s[it-1][1]}} }
class X253 { fun minMeetingRooms(a:Array<IntArray>):Int {val q=PriorityQueue<Int>();for(x in a.sortedBy{it[0]}){if(q.peek()!=null&&q.peek()<=x[0])q.remove();q+=x[1]};return q.size} }
class X1851 { fun minInterval(a:Array<IntArray>,q:IntArray):IntArray {val s=a.sortedBy{it[0]};val out=IntArray(q.size);val h=PriorityQueue<Pair<Int,Int>>(compareBy{it.first});var i=0;for(indexed in q.withIndex().sortedBy{it.value}){val v=indexed.value;val idx=indexed.index;while(i<s.size&&s[i][0]<=v){h+=(s[i][1]-s[i][0]+1 to s[i][1]);i++};while(h.isNotEmpty()&&h.peek().second<v)h.remove();out[idx]=h.peek()?.first?:-1};return out} }
class X202 { fun isHappy(n:Int):Boolean {fun next(x:Int):Int { return x.toString().sumOf { c -> (c-'0')*(c-'0') } };var x=n;val seen=HashSet<Int>();while(x!=1&&seen.add(x))x=next(x);return x==1} }
class X66 { fun plusOne(a:IntArray):IntArray {for(i in a.lastIndex downTo 0)if(a[i]<9){a[i]++;return a}else a[i]=0;return intArrayOf(1)+a} }
class X50 { fun myPow(x:Double,n:Int):Double {var a=x;var k=n.toLong();if(k<0){a=1/a;k=-k};var r=1.0;while(k>0){if(k%2==1L)r*=a;a*=a;k/=2};return r} }
class X43 { fun multiply(a:String,b:String):String {if(a=="0"||b=="0")return "0";val d=IntArray(a.length+b.length);for(i in a.lastIndex downTo 0)for(j in b.lastIndex downTo 0){val p=(a[i]-'0')*(b[j]-'0')+d[i+j+1];d[i+j+1]=p%10;d[i+j]+=p/10};return d.joinToString("").trimStart('0')} }
class X2013 { private val m=HashMap<Pair<Int,Int>,Int>();fun add(p:IntArray){val k=p[0] to p[1];m[k]=(m[k]?:0)+1};fun count(p:IntArray):Int{var r=0;for((q,n)in m)if(q.second==p[1]&&q.first!=p[0]){val d=abs(q.first-p[0]);r+=n*(m[p[0] to (p[1]+d)]?:0)*(m[q.first to (p[1]+d)]?:0);r+=n*(m[p[0] to (p[1]-d)]?:0)*(m[q.first to (p[1]-d)]?:0)};return r} }
class X191 { fun hammingWeight(n:Int):Int=n.countOneBits() }
class X268 { fun missingNumber(a:IntArray):Int {var x=a.size;for(i in a.indices)x=x xor i xor a[i];return x} }
class X7 {
    fun reverse(x: Int): Int {
        var n = x
        var result = 0L
        while (n != 0) { result = result * 10 + n % 10; n /= 10 }
        return if (result < Int.MIN_VALUE.toLong() || result > Int.MAX_VALUE.toLong()) 0 else result.toInt()
    }
}
